name: snekky

on: [push]

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.1.3

      - name: Build
        run: |
          haxelib install console.hx
          haxe build.hxml