name: snekky

on: [push]

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.1.3
      - name: Install dependencies
        run: |
          haxelib install console.hx
          haxelib install hxcpp

      - name: Build
        run: haxe build.hxml

      - name: Upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: snekky-linux
          path: cpp/Snekky
  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.1.3
      - name: Install dependencies
        run: |
          haxelib install console.hx
          haxelib install hxcpp

      - name: Build
        run: haxe build.hxml

      - name: Upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: snekky-win
          path: cpp/Snekky.exe
  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.1.3
      - name: Install dependencies
        run: |
          haxelib install console.hx
          haxelib install hxcpp

      - name: Build
        run: haxe build.hxml

      - name: Upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: snekky-macos
          path: cpp/Snekky